export const productTypes = [
  { label: "Blush", value: "blush" },
  { label: "Bronzer", value: "bronzer" },
  { label: "Eyebrow", value: "eyebrow" },
  { label: "Eyeliner", value: "eyeliner" },
  { label: "Eyeshadow", value: "eyeshadow" },
  { label: "Foundation", value: "foundation" },
  { label: "Lip Liner", value: "lip_liner" },
  { label: "Lipstick", value: "lipstick" },
  { label: "Mascara", value: "mascara" },
  { label: "Nail Polish", value: "nail_polish" },
];

export const categories = [
  { label: "Pencil", value: "pencil" },
  { label: "Lipstick", value: "lipstick" },
  { label: "Liquid", value: "liquid" },
  { label: "Powder", value: "powder" },
  { label: "Lip Gloss", value: "lip_gloss" },
  { label: "Gel", value: "gel" },
  { label: "Cream", value: "cream" },
  { label: "Palette", value: "palette" },
  { label: "Concealer", value: "concealer" },
  { label: "Highlighter", value: "highlighter" },
  { label: "BB/CC", value: "bb_cc" },
  { label: "Contour", value: "contour" },
  { label: "Lip Stain", value: "lip_stain" },
  { label: "Mineral", value: "mineral" },
];
export const brands = [
  { label: "ColourPop", value: "colourpop" },
  { label: "Boosh", value: "boosh" },
  { label: "Deciem", value: "deciem" },
  { label: "Zorah Biocosmétiques", value: "zorah biocosmetiques" },
  { label: "W3LL PEOPLE", value: "w3llpeople" },
  { label: "Sally B's Skin Yummies", value: "sally b's skin yummies" },
  { label: "Rejuva Minerals", value: "rejuva minerals" },
  { label: "Penny Lane Organics", value: "penny lane organics" },
  { label: "Nudus", value: "nudus" },
  { label: "MarieNatie", value: "marienatie" },
  { label: "Maia's Mineral Galaxy", value: "maia's mineral galaxy" },
  { label: "Lotus Cosmetics USA", value: "lotus cosmetics usa" },
  { label: "Green People", value: "green people" },
  { label: "Coastal Classic Creation", value: "coastal classic creation" },
  { label: "C'est Moi", value: "c'est moi" },
  { label: "Alva", value: "alva" },
  { label: "Glossier", value: "glossier" },
  { label: "NYX", value: "nyx" },
  { label: "Fenty", value: "fenty" },
  { label: "Clinique", value: "clinique" },
  { label: "Dior", value: "dior" },
  { label: "Iman", value: "iman" },
  { label: "Benefit", value: "benefit" },
  { label: "Smashbox", value: "smashbox" },
  { label: "Marcelle", value: "marcelle" },
  { label: "Stila", value: "stila" },
  { label: "Mineral Fusion", value: "mineral fusion" },
  { label: "Annabelle", value: "annabelle" },
  { label: "Dr. Hauschka", value: "dr. hauschka" },
  { label: "Physicians Formula", value: "physicians formula" },
  { label: "Cargo Cosmetics", value: "cargo cosmetics" },
  { label: "CoverGirl", value: "covergirl" },
  { label: "E.L.F.", value: "e.l.f." },
  { label: "Maybelline", value: "maybelline" },
  { label: "Almay", value: "almay" },
  { label: "Milani", value: "milani" },
  { label: "Pure Anada", value: "pure anada" },
  { label: "L'Oréal", value: "l'oreal" },
  { label: "Sante", value: "sante" },
  { label: "Revlon", value: "revlon" },
  { label: "Anna Sui", value: "anna sui" },
  { label: "Wet n Wild", value: "wet n wild" },
  { label: "Pacifica", value: "pacifica" },
  { label: "Mistura", value: "mistura" },
  { label: "Zorah", value: "zorah" },
  { label: "Suncoat", value: "suncoat" },
  { label: "Moov", value: "moov" },
  { label: "Misa", value: "misa" },
  { label: "Salon Perfect", value: "salon perfect" },
  { label: "Orly", value: "orly" },
  { label: "China Glaze", value: "china glaze" },
  { label: "Essie", value: "essie" },
  { label: "Butter London", value: "butter london" },
  { label: "Sinful Colours", value: "sinful colours" },
  { label: "Piggy Paint", value: "piggy paint" },
  { label: "DaiSh", value: "dalish" },
  { label: "Burt's Bees", value: "burt's bees" },
];
export const tags = [
  { label: "Cruelty Free", value: "cruelty free" },
  { label: "Vegan", value: "vegan" },
  { label: "Chemical Free", value: "chemical free" },
  { label: "Organic", value: "organic" },
  { label: "Water Free", value: "water free" },
  { label: "Alcohol Free", value: "alcohol free" },
  { label: "Oil Free", value: "oil free" },
  { label: "Silicone Free", value: "silicone free" },
  { label: "Gluten Free", value: "gluten free" },
  { label: "PurPicks", value: "purpicks" },
  { label: "EcoCert", value: "ecocert" },
  { label: "EWG Verified", value: "ewg verified" },
  { label: "Hypoallergenic", value: "hypoallergenic" },
  { label: "No Talc", value: "no talc" },
  { label: "CertClean", value: "certclean" },
  { label: "USDA Organic", value: "usda organic" },
  { label: "Canadian", value: "canadian" },
  { label: "Natural", value: "natural" },
  { label: "Non-GMO", value: "non-gmo" },
  { label: "Fair Trade", value: "fair trade" },
  { label: "Sugar Free", value: "sugar free" },
  { label: "Dairy Free", value: "dairy free" },
  { label: "Peanut Free Product", value: "peanut free product" },
];

export const sortedBy = [
  { label: "newest first", value: "date, DESC" },
  { label: "oldest first", value: "date, ASC" },
  { label: "name A to Z", value: "name, ASC" },
  { label: "name Z to A", value: "name, DESC" },
  { label: "price high to low", value: "price, DESC" },
  { label: "price low to high", value: "price, ASC" },
];

export const pageItemToShow = [10, 20, 30, 40];

 

export const profileMenu = [
  { label: "account main", path: "" },
  { label: "orders", path: "orders" },
  { label: "address book", path: "address" },
];
